/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceOrdersRouteImport } from './routes/service-orders'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as CadastroFerramentasRouteImport } from './routes/cadastro-ferramentas'
import { Route as CadastroEpisRouteImport } from './routes/cadastro-epis'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlmoxarifadosRouteImport } from './routes/almoxarifados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as MovementsIndexRouteImport } from './routes/movements.index'
import { Route as AlmoxarifadosIndexRouteImport } from './routes/almoxarifados.index'
import { Route as StaffIdRouteImport } from './routes/staff.$id'
import { Route as MovementsReturnRouteImport } from './routes/movements.return'
import { Route as MovementsNewRouteImport } from './routes/movements.new'
import { Route as MovementsExitRouteImport } from './routes/movements.exit'
import { Route as AlmoxarifadosIdRouteImport } from './routes/almoxarifados.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceOrdersRoute = ServiceOrdersRouteImport.update({
  id: '/service-orders',
  path: '/service-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroFerramentasRoute = CadastroFerramentasRouteImport.update({
  id: '/cadastro-ferramentas',
  path: '/cadastro-ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEpisRoute = CadastroEpisRouteImport.update({
  id: '/cadastro-epis',
  path: '/cadastro-epis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmoxarifadosRoute = AlmoxarifadosRouteImport.update({
  id: '/almoxarifados',
  path: '/almoxarifados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const MovementsIndexRoute = MovementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MovementsRoute,
} as any)
const AlmoxarifadosIndexRoute = AlmoxarifadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlmoxarifadosRoute,
} as any)
const StaffIdRoute = StaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffRoute,
} as any)
const MovementsReturnRoute = MovementsReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => MovementsRoute,
} as any)
const MovementsNewRoute = MovementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MovementsRoute,
} as any)
const MovementsExitRoute = MovementsExitRouteImport.update({
  id: '/exit',
  path: '/exit',
  getParentRoute: () => MovementsRoute,
} as any)
const AlmoxarifadosIdRoute = AlmoxarifadosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlmoxarifadosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almoxarifados': typeof AlmoxarifadosRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro-epis': typeof CadastroEpisRoute
  '/cadastro-ferramentas': typeof CadastroFerramentasRoute
  '/monitoring': typeof MonitoringRoute
  '/movements': typeof MovementsRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/service-orders': typeof ServiceOrdersRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/users': typeof UsersRoute
  '/almoxarifados/$id': typeof AlmoxarifadosIdRoute
  '/movements/exit': typeof MovementsExitRoute
  '/movements/new': typeof MovementsNewRoute
  '/movements/return': typeof MovementsReturnRoute
  '/staff/$id': typeof StaffIdRoute
  '/almoxarifados/': typeof AlmoxarifadosIndexRoute
  '/movements/': typeof MovementsIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro-epis': typeof CadastroEpisRoute
  '/cadastro-ferramentas': typeof CadastroFerramentasRoute
  '/monitoring': typeof MonitoringRoute
  '/permissions': typeof PermissionsRoute
  '/service-orders': typeof ServiceOrdersRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/almoxarifados/$id': typeof AlmoxarifadosIdRoute
  '/movements/exit': typeof MovementsExitRoute
  '/movements/new': typeof MovementsNewRoute
  '/movements/return': typeof MovementsReturnRoute
  '/staff/$id': typeof StaffIdRoute
  '/almoxarifados': typeof AlmoxarifadosIndexRoute
  '/movements': typeof MovementsIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almoxarifados': typeof AlmoxarifadosRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro-epis': typeof CadastroEpisRoute
  '/cadastro-ferramentas': typeof CadastroFerramentasRoute
  '/monitoring': typeof MonitoringRoute
  '/movements': typeof MovementsRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/service-orders': typeof ServiceOrdersRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/users': typeof UsersRoute
  '/almoxarifados/$id': typeof AlmoxarifadosIdRoute
  '/movements/exit': typeof MovementsExitRoute
  '/movements/new': typeof MovementsNewRoute
  '/movements/return': typeof MovementsReturnRoute
  '/staff/$id': typeof StaffIdRoute
  '/almoxarifados/': typeof AlmoxarifadosIndexRoute
  '/movements/': typeof MovementsIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almoxarifados'
    | '/auth'
    | '/cadastro-epis'
    | '/cadastro-ferramentas'
    | '/monitoring'
    | '/movements'
    | '/permissions'
    | '/service-orders'
    | '/settings'
    | '/staff'
    | '/users'
    | '/almoxarifados/$id'
    | '/movements/exit'
    | '/movements/new'
    | '/movements/return'
    | '/staff/$id'
    | '/almoxarifados/'
    | '/movements/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro-epis'
    | '/cadastro-ferramentas'
    | '/monitoring'
    | '/permissions'
    | '/service-orders'
    | '/settings'
    | '/users'
    | '/almoxarifados/$id'
    | '/movements/exit'
    | '/movements/new'
    | '/movements/return'
    | '/staff/$id'
    | '/almoxarifados'
    | '/movements'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/almoxarifados'
    | '/auth'
    | '/cadastro-epis'
    | '/cadastro-ferramentas'
    | '/monitoring'
    | '/movements'
    | '/permissions'
    | '/service-orders'
    | '/settings'
    | '/staff'
    | '/users'
    | '/almoxarifados/$id'
    | '/movements/exit'
    | '/movements/new'
    | '/movements/return'
    | '/staff/$id'
    | '/almoxarifados/'
    | '/movements/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmoxarifadosRoute: typeof AlmoxarifadosRouteWithChildren
  AuthRoute: typeof AuthRoute
  CadastroEpisRoute: typeof CadastroEpisRoute
  CadastroFerramentasRoute: typeof CadastroFerramentasRoute
  MonitoringRoute: typeof MonitoringRoute
  MovementsRoute: typeof MovementsRouteWithChildren
  PermissionsRoute: typeof PermissionsRoute
  ServiceOrdersRoute: typeof ServiceOrdersRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-orders': {
      id: '/service-orders'
      path: '/service-orders'
      fullPath: '/service-orders'
      preLoaderRoute: typeof ServiceOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-ferramentas': {
      id: '/cadastro-ferramentas'
      path: '/cadastro-ferramentas'
      fullPath: '/cadastro-ferramentas'
      preLoaderRoute: typeof CadastroFerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-epis': {
      id: '/cadastro-epis'
      path: '/cadastro-epis'
      fullPath: '/cadastro-epis'
      preLoaderRoute: typeof CadastroEpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almoxarifados': {
      id: '/almoxarifados'
      path: '/almoxarifados'
      fullPath: '/almoxarifados'
      preLoaderRoute: typeof AlmoxarifadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/movements/': {
      id: '/movements/'
      path: '/'
      fullPath: '/movements/'
      preLoaderRoute: typeof MovementsIndexRouteImport
      parentRoute: typeof MovementsRoute
    }
    '/almoxarifados/': {
      id: '/almoxarifados/'
      path: '/'
      fullPath: '/almoxarifados/'
      preLoaderRoute: typeof AlmoxarifadosIndexRouteImport
      parentRoute: typeof AlmoxarifadosRoute
    }
    '/staff/$id': {
      id: '/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof StaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/movements/return': {
      id: '/movements/return'
      path: '/return'
      fullPath: '/movements/return'
      preLoaderRoute: typeof MovementsReturnRouteImport
      parentRoute: typeof MovementsRoute
    }
    '/movements/new': {
      id: '/movements/new'
      path: '/new'
      fullPath: '/movements/new'
      preLoaderRoute: typeof MovementsNewRouteImport
      parentRoute: typeof MovementsRoute
    }
    '/movements/exit': {
      id: '/movements/exit'
      path: '/exit'
      fullPath: '/movements/exit'
      preLoaderRoute: typeof MovementsExitRouteImport
      parentRoute: typeof MovementsRoute
    }
    '/almoxarifados/$id': {
      id: '/almoxarifados/$id'
      path: '/$id'
      fullPath: '/almoxarifados/$id'
      preLoaderRoute: typeof AlmoxarifadosIdRouteImport
      parentRoute: typeof AlmoxarifadosRoute
    }
  }
}

interface AlmoxarifadosRouteChildren {
  AlmoxarifadosIdRoute: typeof AlmoxarifadosIdRoute
  AlmoxarifadosIndexRoute: typeof AlmoxarifadosIndexRoute
}

const AlmoxarifadosRouteChildren: AlmoxarifadosRouteChildren = {
  AlmoxarifadosIdRoute: AlmoxarifadosIdRoute,
  AlmoxarifadosIndexRoute: AlmoxarifadosIndexRoute,
}

const AlmoxarifadosRouteWithChildren = AlmoxarifadosRoute._addFileChildren(
  AlmoxarifadosRouteChildren,
)

interface MovementsRouteChildren {
  MovementsExitRoute: typeof MovementsExitRoute
  MovementsNewRoute: typeof MovementsNewRoute
  MovementsReturnRoute: typeof MovementsReturnRoute
  MovementsIndexRoute: typeof MovementsIndexRoute
}

const MovementsRouteChildren: MovementsRouteChildren = {
  MovementsExitRoute: MovementsExitRoute,
  MovementsNewRoute: MovementsNewRoute,
  MovementsReturnRoute: MovementsReturnRoute,
  MovementsIndexRoute: MovementsIndexRoute,
}

const MovementsRouteWithChildren = MovementsRoute._addFileChildren(
  MovementsRouteChildren,
)

interface StaffRouteChildren {
  StaffIdRoute: typeof StaffIdRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIdRoute: StaffIdRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmoxarifadosRoute: AlmoxarifadosRouteWithChildren,
  AuthRoute: AuthRoute,
  CadastroEpisRoute: CadastroEpisRoute,
  CadastroFerramentasRoute: CadastroFerramentasRoute,
  MonitoringRoute: MonitoringRoute,
  MovementsRoute: MovementsRouteWithChildren,
  PermissionsRoute: PermissionsRoute,
  ServiceOrdersRoute: ServiceOrdersRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
